version: '3.8'

services:
  app:
    container_name: ai
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      TZ: Asia/Tokyo
      USERS: yude_jp
    restart: unless-stopped
